### ISSUE TITLE
Date/Time Picker

### ISSUE THREAD

**Issue by ZHollingshead** [aurelia/ux#90]
Implement the ux-datepicker component for Material and iOS design.  
### Todo  
- [x] Material
- [x] Accessibility  
- [ ] Documentation

### Design Guidelines:
- [iOS Pickers](https://developer.apple.com/ios/human-interface-guidelines/ui-controls/pickers/)  
- [Material Pickers](https://material.io/guidelines/components/pickers.html)

### Features
- [x] Date range: min/start and max/end selectable dates
- [x] Multiple select types: Date, Time, DateTime
- [x] 12 hour or 24 hour time formats
- [x] Initial date: defaults to today
- [x] Time range: min/start and max/end selectable time
- [x] Custom formatters and parsers
- [x] Disable dates: days of the week, holidays, etc

**Comment by ZHollingshead** [comment]
Feature Ideas

- Date range: min and max selectable dates
- Time range: min and max selectable time
- Initial date: defaults to today
- Multiple select types: Date, Time, DateTime
- Disable dates: days of the week, holidays, etc
- RTL support

**Comment by JoshuaVSherman** [comment]
specify start and end date, where end date cannot be before start date
time can be in 12 hour am/pm or military 24hr time

**Comment by lstarky** [comment]
i18n / world language support

**Comment by zewa666** [comment]
@ZHollingshead date and time ranges ... absolutely would love to see that

**Comment by ZHollingshead** [comment]
Issue moved to [aurelia/ux-components #3](https://github.com/aurelia/ux-components/issues/3) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ZHollingshead** [comment]
Issue moved to [aurelia/ux-components #7](https://github.com/aurelia/ux-components/issues/7) via [**ZenHub**](https://www.zenhub.com/)
